### PR TITLE
Revert "Merge `NetlinkPayload::{Ack,Error}`"

### PR DESCRIPTION
**Pull request by cathay4t**
This reverts commit 52732b3fc4bc5671c8ff6d2d724a95f44d82043e.

### CODE REVIEW

**Comment by cathay4t** [comment]
Detail on this revert is explained at https://github.com/rust-netlink/netlink-packet-core/pull/16#issuecomment-1627584529

**Comment by ghananigans** [comment]
Hey Cathay!

I responded to your comment in #16, but if you prefer we can continue discussion here?

**Comment by cathay4t** [comment]
Let's keep the disucssion in #16 to make the context in single place.

**Comment by cathay4t** [comment]
Force merging before people using git dependency changed their code before we made decision.

**Pull request merged**
